/**
 * DBServiceSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package net.i2cat.csade.life2.backoffice.clientws.b.dbservice;

public interface DBServiceSoap extends java.rmi.Remote {
    public int dbRegisterUser(java.lang.String login, java.lang.String role, java.lang.String password, java.lang.String name, java.lang.String email, java.lang.String telephonenumber, java.lang.String language, java.lang.String home_area_lat, java.lang.String home_area_lon, java.lang.String home_area_radius, java.lang.String notification_level, java.lang.String region, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int dbUpdateUser(java.lang.String login, java.lang.String role, java.lang.String password, java.lang.String name, java.lang.String email, java.lang.String telephonenumber, java.lang.String picture, java.lang.String language, java.lang.String home_area_lat, java.lang.String home_area_lon, java.lang.String home_area_radius, java.lang.String last_location_timestamp, java.lang.String last_location_lat, java.lang.String last_location_lon, java.lang.String notification_level, java.lang.String promoter_id, java.lang.String user_average_mark, java.lang.String user_votes, int enabled, int skillsVisibility, int interestsVisibility, java.lang.String region, java.lang.String address, java.lang.String adminRegion, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int dbUserLogin(java.lang.String login, java.lang.String password, javax.xml.rpc.holders.IntHolder role, javax.xml.rpc.holders.StringHolder email, javax.xml.rpc.holders.StringHolder telephonenumber, javax.xml.rpc.holders.StringHolder name, javax.xml.rpc.holders.StringHolder picture, javax.xml.rpc.holders.StringHolder language, javax.xml.rpc.holders.StringHolder home_area_lat, javax.xml.rpc.holders.StringHolder home_area_lon, javax.xml.rpc.holders.StringHolder home_area_radius, javax.xml.rpc.holders.StringHolder last_location_timestamp, javax.xml.rpc.holders.StringHolder last_location_lat, javax.xml.rpc.holders.StringHolder last_location_lon, javax.xml.rpc.holders.StringHolder notification_level, javax.xml.rpc.holders.StringHolder promoter_id, javax.xml.rpc.holders.StringHolder user_average_mark, javax.xml.rpc.holders.StringHolder user_votes, javax.xml.rpc.holders.IntHolder enabled, javax.xml.rpc.holders.StringHolder region, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int dbDeleteUser(java.lang.String login, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int dbSetSkillsVisiblity(java.lang.String login, int visibility, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int dbSetInterestsVisiblity(java.lang.String login, int visibility, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int dbReadUser(java.lang.String login, javax.xml.rpc.holders.IntHolder role, javax.xml.rpc.holders.StringHolder email, javax.xml.rpc.holders.StringHolder name, javax.xml.rpc.holders.StringHolder picture, javax.xml.rpc.holders.StringHolder language, javax.xml.rpc.holders.StringHolder telephonenumber, javax.xml.rpc.holders.StringHolder home_area_lat, javax.xml.rpc.holders.StringHolder home_area_lon, javax.xml.rpc.holders.StringHolder home_area_radius, javax.xml.rpc.holders.StringHolder last_location_timestamp, javax.xml.rpc.holders.StringHolder last_location_lat, javax.xml.rpc.holders.StringHolder last_location_lon, javax.xml.rpc.holders.StringHolder notification_level, javax.xml.rpc.holders.StringHolder promoter_id, javax.xml.rpc.holders.StringHolder user_average_mark, javax.xml.rpc.holders.StringHolder user_votes, javax.xml.rpc.holders.IntHolder enabled, javax.xml.rpc.holders.StringHolder region, javax.xml.rpc.holders.StringHolder address, javax.xml.rpc.holders.IntHolder skillsVisibility, javax.xml.rpc.holders.IntHolder interestsVisibility, javax.xml.rpc.holders.StringHolder adminRegion, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getUserList(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.dbservice.holders.ArrayOfUserProfileHolder ret_UserList, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int uploadPicture(java.lang.String login, byte[] picture, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
}
