LIFE20: Nuevo usuario registrado

Login de usuario: {#UserLogin#}

Nombre de usuario: {#UserName#}

Identidad de usuario: {#UserId#}

Rol de usuario: {#UserRole#}

e-mail de usuario: {#Email#}

--
This message is automatically generated by LIFE20.
If you think it was sent incorrectly, please contact your LIFE20 administrators