/**
 * ENGServiceSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package net.i2cat.csade.life2.backoffice.clientws.b.engservice;

public interface ENGServiceSoap extends java.rmi.Remote {
    public int submitOffer(java.lang.String login, int request_id, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Offer, java.lang.String where_Offer, java.util.Calendar deadline, int contactType, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getOffer(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfOfferHolder ret_Offer, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int submitRequest(java.lang.String login, java.lang.String request_Type, java.lang.String category_id, java.lang.String short_description, java.lang.String description, java.lang.String when_request, java.lang.String where, net.i2cat.csade.life2.backoffice.clientws.b.engservice.FilteringPrefs filtering_preferences, java.lang.String deadline, java.lang.String candidates, int contactType, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateRequest(java.lang.String login, java.lang.String request_id, java.lang.String request_Type, java.lang.String category_id, java.lang.String short_description, java.lang.String description, java.lang.String when_request, java.lang.String where, net.i2cat.csade.life2.backoffice.clientws.b.engservice.FilteringPrefs filtering_preferences, java.lang.String deadline, java.lang.String candidates, net.i2cat.csade.life2.backoffice.clientws.b.engservice.Status sStatus, int contactType, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteRequest(java.lang.String login, java.lang.String request_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int applyForRequest(java.lang.String login, java.lang.String request_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int unApplyForRequest(java.lang.String login, java.lang.String request_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getRequestStatus(java.lang.String login, java.lang.String request_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getRequests(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfRequestHolder ret_Requests, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getRegions(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfRegionsHolder ret_Regions, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getRecommendations(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfRecommendationsHolder ret_Recs, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int joinActivity(java.lang.String login, java.lang.String offer_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int unJoinActivity(java.lang.String login, java.lang.String offer_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int moderateJoinActivity(java.lang.String login, java.lang.String offer_id, java.lang.String requested_id, int moderation, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int sendFeedback(java.lang.String login, java.lang.String offer_id, int feedback, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int sendRecommendation(java.lang.String login, java.lang.String offer_id, java.lang.String request_id, java.lang.String comment, java.lang.String reclist, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int promoterFeedback(java.lang.String login, java.lang.String user_id, int feedback, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int acceptRejectRequest(java.lang.String login, java.lang.String user_id, java.lang.String request_id, int acceptReject, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addSkill(java.lang.String login, java.lang.String skill, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addInterest(java.lang.String login, java.lang.String interest, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getJoins(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfJoinHolder ret_joins, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getSkills(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfSkillHolder ret_skills, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getInterests(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfInterestHolder ret_interest, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getMessages(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfMessagesHolder ret_messages, int start, int count, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateMessage(int id, int MRead, int MReplied) throws java.rmi.RemoteException;
    public int updateSkill(java.lang.String login, java.lang.String skill_id, java.lang.String skill, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateInterest(java.lang.String login, java.lang.String interest_id, java.lang.String interest, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteSkill(java.lang.String login, java.lang.String skill_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteMessage(int id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteInterest(java.lang.String login, java.lang.String interest_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addCategory(java.lang.String login, java.lang.String category, java.lang.String category_desc, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addActCategory(java.lang.String login, java.lang.String category, java.lang.String category_desc, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addCompCategory(java.lang.String login, java.lang.String category, java.lang.String category_desc, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addRegion(java.lang.String login, java.lang.String name, java.lang.String country, java.lang.String country_code, java.lang.String lat, java.lang.String lon, java.lang.String radius, java.lang.String lng, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addHub(java.lang.String login, int user_id, java.lang.String name, int area, java.lang.String lng, int category, java.lang.String address, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addBusiness(java.lang.String login, int user_id, java.lang.String name, int area, java.lang.String lng, int category, java.lang.String address, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getHub(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfHubHolder ret_hub, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getBusiness(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfBusinessHolder ret_business, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getCategories(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfCategoryHolder ret_categories, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getActCategories(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfCategoryHolder ret_categories, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getCompCategories(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfCategoryHolder ret_categories, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateCategory(java.lang.String login, java.lang.String category_id, java.lang.String category_name, java.lang.String category_desc, int status, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateActCategory(java.lang.String login, java.lang.String category_id, java.lang.String category_name, java.lang.String category_desc, int status, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateCompCategory(java.lang.String login, java.lang.String category_id, java.lang.String category_name, java.lang.String category_desc, int status, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateRegion(java.lang.String login, java.lang.String id, java.lang.String name, java.lang.String country, java.lang.String country_code, java.lang.String lat, java.lang.String lon, java.lang.String radius, java.lang.String lng, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteRegion(java.lang.String login, java.lang.String id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteCategory(java.lang.String login, java.lang.String category_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteActCategory(java.lang.String login, java.lang.String category_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteCompCategory(java.lang.String login, java.lang.String category_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteRecommendation(java.lang.String login, java.lang.String rec_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addActivity(java.lang.String login, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Activity, java.lang.String where_Activity, java.util.Calendar deadline, int contactType, java.lang.String orgName, java.lang.String title, java.util.Calendar dateOfActivity, java.lang.String address, java.lang.String telephone, java.lang.String price, int subscription, int maxParticipants, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addMpOffer(java.lang.String login, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_MpOffer, java.lang.String where_MpOffer, java.util.Calendar deadline, int contactType, java.lang.String orgName, java.lang.String title, java.util.Calendar dateOfOffer, java.lang.String address, java.lang.String telephone, java.lang.String mobile, java.lang.String email, java.lang.String url_booking, java.lang.String url_web, java.lang.String url_brochure, java.lang.String price, int subscription, int maxParticipants, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getActivities(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfActivityHolder ret_Activities, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getMpOffers(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfMpOfferHolder ret_mpOffers, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateHub(java.lang.String login, int hub_id, java.lang.String name, int user_id, int area, java.lang.String hub_average_mark, int hub_votes, java.lang.String lng, int category, java.lang.String address, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateBusiness(java.lang.String login, int SB_id, java.lang.String name, int user_id, int area, java.lang.String SB_average_mark, int SB_votes, java.lang.String lng, int category, java.lang.String address, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateActivity(java.lang.String login, int activity_id, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Activity, java.lang.String where_Activity, java.util.Calendar deadline, int contactType, java.lang.String orgName, java.lang.String title, java.util.Calendar dateOfActivity, java.lang.String address, java.lang.String telephone, java.lang.String price, int subscription, int maxParticipants, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateMpOffer(java.lang.String login, int offer_id, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Offer, java.lang.String where_Offer, java.util.Calendar deadline, int contactType, java.lang.String orgName, java.lang.String title, java.util.Calendar dateOfOffer, java.lang.String address, java.lang.String telephone, java.lang.String mobile, java.lang.String email, java.lang.String url_booking, java.lang.String url_web, java.lang.String url_brochure, java.lang.String price, int subscription, int maxParticipants, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int viewOffer(java.lang.String login, int offer_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateOffer(java.lang.String login, int offer_id, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Offer, java.lang.String where_Offer, java.util.Calendar deadline, int contactType, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteHub(java.lang.String login, int hub_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteBusiness(java.lang.String login, int SB_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteActivity(java.lang.String login, int activity_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addService(java.lang.String login, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Service, java.lang.String where_Service, java.util.Calendar deadline, int contactType, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getServices(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfServiceHolder ret_Services, int start, int count, java.lang.String username, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int updateService(java.lang.String login, java.lang.String service_id, java.lang.String category, java.lang.String short_desc, java.lang.String detailed_info, java.lang.String when_Service, java.lang.String where_Service, java.util.Calendar deadline, int contactType, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteService(java.lang.String login, java.lang.String service_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int deleteOffer(java.lang.String login, java.lang.String offer_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int applyForOffer(java.lang.String login, java.lang.String offer_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int unApplyForOffer(java.lang.String login, java.lang.String offer_id, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int acceptRejectNewCategory(java.lang.String login, java.lang.String user_id, java.lang.String category_id, int acceptReject, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int addStat(java.lang.String login, java.lang.String event_id, java.util.Calendar time, int duration, java.lang.String location_lat, java.lang.String location_lon, java.lang.String device, java.lang.String query, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getStats(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfStatsHolder ret_Stats, int start, int count, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public int getStatsSql(java.lang.String sql, net.i2cat.csade.life2.backoffice.clientws.b.engservice.holders.ArrayOfObjStatsHolder ret_Stats, javax.xml.rpc.holders.StringHolder errorMessage) throws java.rmi.RemoteException;
    public java.lang.String sendMessage(java.lang.String login, java.lang.String dest, java.lang.String message, int offer_id, int req_id) throws java.rmi.RemoteException;
}
