LIFE20: Actividad creada o actualizada

Nombre de usuario: {#UserName#}

Identidad de usuario: {#UserId#}

Identidad de Actividad: {#IdItem#}

Actividad: {#ShortDesc#}

Descripción: {#LongDesc#}

--
This message is automatically generated by LIFE20.
If you think it was sent incorrectly, please contact your LIFE20 administrators