LIFE20: Un usuario desea unirse a una actividad

Nombre de Usuario: {#UserName#}

Identidad de Usuario: {#UserId#}

Identidad de la Actividad: {#IdItem#}

Actividad: {#ShortDesc#}

Descripción: {#LongDesc#}

--
This message is automatically generated by LIFE20.
If you think it was sent incorrectly, please contact your LIFE20 administrators