LIFE20: Habilidad creada o actualizada

Nombre de usuario: {#UserName#}

Identidad de usuario: {#UserId#}

Identidad de Habilidad: {#IdItem#}

Habilidad: {#ShortDesc#}

Descripción: {#LongDesc#}

--
This message is automatically generated by LIFE20.
If you think it was sent incorrectly, please contact your LIFE20 administrators