LIFE20: Un usuario ha enviado una petición

Nombre de usuario: {#UserName#}

Identidad de usuario: {#UserId#}

Identidad de Petición: {#IdItem#}

Petición: {#ShortDesc#}

Descripción: {#LongDesc#}

--
This message is automatically generated by LIFE20.
If you think it was sent incorrectly, please contact your LIFE20 administrators