LIFE20: Servicio creado o actualizado

Nombre de usuario: {#UserName#}

Identidad de usuario: {#UserId#}

Identidad de servicio: {#IdItem#}

Servicio: {#ShortDesc#}

Descripción: {#LongDesc#}

--
This message is automatically generated by LIFE20.
If you think it was sent incorrectly, please contact your LIFE20 administrators